### ISSUE TITLE
I can hear my breathing in the speaker if IntelliJ is opened.

### ISSUE THREAD

**Issue by szigya** [OpenASR/idiolect#28]
I don't know if it is something which supposed to be like this, but when I run IntelliJ, my microphone is on and I can hear as I'm breathing. It doesn't matter if the plugin is recording or not.

**Comment by mzyil** [comment]
open recording devices by right clicking sound icon in the system tray. Then right click your microphone and select properties. disable listen to this microphone from listen tab.

**Comment by breandan** [comment]
Thanks for your feedback and sorry about the delay. We recently rewrote Idear from scratch using the [Vosk speech recognizer](https://alphacephei.com/vosk/) and published a [new plugin](https://plugins.jetbrains.com/plugin/20776-idiolect) along with some example commands in [the docs](https://github.com/OpenASR/idiolect/blob/master/docs/example-phrases.md). If your issue persists or you get a chance to try it out and have other feedback, please drop us a line. Thanks!
