### ISSUE TITLE
no mic button on toolbar

### ISSUE THREAD

**Issue by ctrl-alt-lulz** [OpenASR/idiolect#60]
no mic button on toolbar, goland. basically cant even use this at all wtf

**Comment by breandan** [comment]
Long story short, we recently rewrote Idear from scratch using the [Vosk speech recognizer](https://alphacephei.com/vosk/) and published a [new plugin](https://plugins.jetbrains.com/plugin/20776-idiolect) along with some example commands in [the docs](https://github.com/OpenASR/idiolect/blob/master/docs/example-phrases.md). The microphone button was moved to the status bar. If you get the chance to try it and have any feedback, feel free to open a new ticket. Cheers!
